/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import clases.obsequios;
import java.awt.Color;
import java.awt.Image;
//import java.awt.event.FocusAdapter;
//import java.awt.event.FocusEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
//import javax.swing.JTextField;

/**
 *
 * @author FRANCIS
 */
public class Obsequios_ extends javax.swing.JFrame {

    /**
     * Creates new form Obsequios_
     */
    
    // se crea dos variables paera almacenar la info del mouse cuando haga clic sobre el panel (header)
    int xMouse, yMouse;
    
    public Obsequios_() {
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(logo, "src/images/logo_empresa.jpeg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtObsequio1 = new javax.swing.JTextField();
        txtObsequio2 = new javax.swing.JTextField();
        txtObsequio3 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        bt = new javax.swing.JPanel();
        txtX = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("1 unidad");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 20));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("2 a 5 unidades");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("6 a más unidades");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txtObsequio1.setForeground(new java.awt.Color(153, 153, 153));
        txtObsequio1.setText("Obsequio 1");
        txtObsequio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObsequio1MousePressed(evt);
            }
        });
        fondo.add(txtObsequio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));

        txtObsequio2.setForeground(new java.awt.Color(153, 153, 153));
        txtObsequio2.setText("Obsequio 2");
        txtObsequio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObsequio2MousePressed(evt);
            }
        });
        fondo.add(txtObsequio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 100, -1));

        txtObsequio3.setForeground(new java.awt.Color(153, 153, 153));
        txtObsequio3.setText("Obsequio 3");
        txtObsequio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObsequio3MousePressed(evt);
            }
        });
        fondo.add(txtObsequio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 100, -1));

        btnAceptar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAceptar.setText("Guardar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        fondo.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, -1));

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        fondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 90, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        bt.setBackground(new java.awt.Color(255, 255, 255));

        txtX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtX.setText("X");
        txtX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btLayout = new javax.swing.GroupLayout(bt);
        bt.setLayout(btLayout);
        btLayout.setHorizontalGroup(
            btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        btLayout.setVerticalGroup(
            btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(488, Short.MAX_VALUE)
                .addComponent(bt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));
        fondo.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 50));

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Configurar Obsequios");
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 40, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     //evento que ayuda a cerrar la ventana 
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    //evento que ayuda a cerrar la ventana 
    private void txtXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtXMouseClicked

    // para que el mouse entre en el pane y de un efecto de color rojo y la x blanco
    private void txtXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseEntered
        // TODO add your handling code here:
        bt.setBackground(Color.red);
        txtX.setForeground(Color.white);
    }//GEN-LAST:event_txtXMouseEntered

    // para que el efecto desaparezca
    private void txtXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseExited
        // TODO add your handling code here:
        bt.setBackground(Color.white);
       txtX.setForeground(Color.black);
    }//GEN-LAST:event_txtXMouseExited


    //Almacenar la pocision del mouse en eje x - eje y
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed
 
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen(), y =evt.getYOnScreen();
        this.setLocation( x- xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

  
    private void txtObsequio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObsequio1MousePressed
        // TODO add your handling code here:
//        configurarPlaceholder(txtObsequio1, "Obsequio 1");
                if(txtObsequio1.getText().equals("Obsequio 1")){
                txtObsequio1.setText("");
                txtObsequio1.setForeground(Color.black);
        }
                if(txtObsequio2.getText().isEmpty()){
                txtObsequio2.setText("Obsequio 2");
                txtObsequio2.setForeground(Color.gray);
       }
                if(txtObsequio3.getText().isEmpty()){
                txtObsequio3.setText("Obsequio 3");
                txtObsequio3.setForeground(Color.gray);
        }           
    }//GEN-LAST:event_txtObsequio1MousePressed

    private void txtObsequio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObsequio2MousePressed
        // TODO add your handling code here:
//        configurarPlaceholder(txtObsequio2, "Obsequio 2");
                if(txtObsequio2.getText().equals("Obsequio 2")){
                txtObsequio2.setText("");
                txtObsequio2.setForeground(Color.black);
        }
                if(txtObsequio1.getText().isEmpty()){
                txtObsequio1.setText("Obsequio 1");
                txtObsequio1.setForeground(Color.gray);
       }
                if(txtObsequio3.getText().isEmpty()){
                txtObsequio3.setText("Obsequio 3");
                txtObsequio3.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtObsequio2MousePressed

    private void txtObsequio3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObsequio3MousePressed
        // TODO add your handling code here:
//        configurarPlaceholder(txtObsequio3, "Obsequio 3");
                if(txtObsequio3.getText().equals("Obsequio 3")){
                txtObsequio3.setText("");
                txtObsequio3.setForeground(Color.black);
        }
                if(txtObsequio2.getText().isEmpty()){
                txtObsequio2.setText("Obsequio 2");
                txtObsequio2.setForeground(Color.gray);
       }
                if(txtObsequio1.getText().isEmpty()){
                txtObsequio1.setText("Obsequio 1");
                txtObsequio1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtObsequio3MousePressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        // Guardar en el objeto usando el constructor
        obsequios obsequios = new obsequios("", "", "");
        //ahora seteamos los valores que el usuario ingreso
        obsequios.setObsequio1(txtObsequio1.getText());
        obsequios.setObsequio2(txtObsequio2.getText());
        obsequios.setObsequio3(txtObsequio3.getText());  
        // Confirmación
        JOptionPane.showMessageDialog(this, "¡Obsequios guardados!");
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Obsequios_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Obsequios_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Obsequios_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Obsequios_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Obsequios_().setVisible(true);
            }
        });
    }
        private void SetImageLabel(JLabel label, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                           image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }    
        
//    public void configurarPlaceholder(JTextField campo, String placeholder) {
//    campo.setText(placeholder);
//    campo.setForeground(Color.GRAY);
//    campo.addFocusListener(new FocusAdapter() {
//        @Override
//        public void focusGained(FocusEvent e) {
//            if (campo.getText().equals(placeholder)) {
//                campo.setText("");
//                campo.setForeground(Color.BLACK);
//            }
//        }
//
//        @Override
//        public void focusLost(FocusEvent e) {
//            if (campo.getText().isEmpty()) {
//                campo.setText(placeholder);
//                campo.setForeground(Color.GRAY);
//            }
//        }
//    });
//}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bt;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtObsequio1;
    private javax.swing.JTextField txtObsequio2;
    private javax.swing.JTextField txtObsequio3;
    private javax.swing.JLabel txtX;
    // End of variables declaration//GEN-END:variables
}
