/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces_Paneles;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import metodo.Conexion;

/**
 *
 * @author FRANCIS
 */
public class lista extends javax.swing.JPanel {
    
    /**
     * Creates new form lista
     */
    public lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mostrarTable = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        mostrarTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mostrarTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarTable.setText("Mostrar");
        mostrarTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarTableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mostrarTable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        table.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scroll.setViewportView(table);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(0, 244, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll)
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));
    }// </editor-fold>//GEN-END:initComponents

   //Thats a method which help me doing a table with my database values
    private void mostrarTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarTableMouseClicked
        // TODO add your handling code here:
        ListarProductosDeBaseDatos();
    }//GEN-LAST:event_mostrarTableMouseClicked

// Metodo para que imprima los datos de la database en formato tabla correctamente
    private void ListarProductosDeBaseDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Codigo");
        modelo.addColumn("Producto");
        modelo.addColumn("Placa");
        modelo.addColumn("Procesador");
        modelo.addColumn("Ram");
        modelo.addColumn("Tarjeta gráfica");
        modelo.addColumn("Almacenamiento");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        
        Conexion conexion = new Conexion();
        Connection conn = conexion.conectar();
        String sql = "Select * from left4tech.producto";
       
        try{
            Statement declaracion =  conn.createStatement();
            ResultSet resultadoSeteado = declaracion.executeQuery(sql); 
            
            while(resultadoSeteado.next()){
              Object []  fila = new Object[10];
              fila[0] = resultadoSeteado.getInt("idproducto");
              fila[1] = resultadoSeteado.getString("cod_producto");
              fila[2] = resultadoSeteado.getString("modelo");
              fila[3] =  resultadoSeteado.getString("placa");
              fila[4] = resultadoSeteado.getString("procesador");
              fila[5] = resultadoSeteado.getString("ram");
              fila[6] = resultadoSeteado.getString("tarjeta_grafica");
              fila[7] = resultadoSeteado.getString("almacenamiento");
              fila[8] = resultadoSeteado.getDouble("precio");
              fila[9] = resultadoSeteado.getInt("stock");
              modelo.addRow(fila);  
            }
            table.setModel(modelo);
            
            resultadoSeteado.close();
            declaracion.close();
            conn.close();
            
        }catch(SQLException e){
            System.out.println("Error al mostrar los productos: " +e.getMessage());
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mostrarTable;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
