package login;

import java.sql.*;
import metodo.Conexion;
import Ventanas.inicio;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import clases.inicioSesion;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCIS
 */
public class Login extends javax.swing.JFrame {
    // La clave para hacer diseños libres es establecer el absolute layout
    // se crea dos variables para almacenar la info del mouse cuando haga clic sobre el pane (header)
    Conexion conexion = new Conexion();
    Connection conn;
    int xMouse, yMouse;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conn = conexion.conectar();
        setIconImage(getIconImage());        
    }
        @Override
        public final  Image getIconImage () {
        Image retValue = Toolkit.getDefaultToolkit().getImage
                                (ClassLoader.getSystemResource("images/logo_empresa.jpeg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        contrat = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        usuart = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        paneldentrar = new javax.swing.JPanel();
        entrar = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        bt = new javax.swing.JPanel();
        txtX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(14, 26, 36));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo2.poo.jpg"))); // NOI18N
        bg.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 210, 570));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("INICIAR SESIÓN");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 210, 50));

        contrat.setBackground(new java.awt.Color(0, 0, 0));
        contrat.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        contrat.setForeground(new java.awt.Color(255, 255, 255));
        contrat.setText("CONTRASEÑA");
        bg.add(contrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 270, 20));
        bg.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 270, 30));

        usuart.setBackground(new java.awt.Color(0, 0, 0));
        usuart.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        usuart.setForeground(new java.awt.Color(255, 255, 255));
        usuart.setText("USUARIO");
        bg.add(usuart, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 270, 20));
        bg.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 260, 40));

        paneldentrar.setBackground(new java.awt.Color(0, 65, 86));

        entrar.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 14)); // NOI18N
        entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrar.setText("ENTRAR");
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneldentrarLayout = new javax.swing.GroupLayout(paneldentrar);
        paneldentrar.setLayout(paneldentrarLayout);
        paneldentrarLayout.setHorizontalGroup(
            paneldentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        paneldentrarLayout.setVerticalGroup(
            paneldentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(paneldentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 100, 40));

        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("********");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        bg.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 260, 30));

        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Ingrese su usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 270, 30));

        header.setBackground(new java.awt.Color(26, 46, 63));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        bt.setBackground(new java.awt.Color(26, 46, 63));

        txtX.setForeground(new java.awt.Color(255, 255, 255));
        txtX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtX.setText("X");
        txtX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btLayout = new javax.swing.GroupLayout(bt);
        bt.setLayout(btLayout);
        btLayout.setHorizontalGroup(
            btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        btLayout.setVerticalGroup(
            btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 488, Short.MAX_VALUE)
                .addComponent(bt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // se almacena la pocision del eje x, y desde la variable (evt) del metedo
    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    // cuando le den click al pane entrar aparezca un JOptionpane de emergencia con los datos
    //tambien entre al programa y posterior se cierre la interfaz de login :)
    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked
        // TODO add your handling code here:
       String usuario = txtUsuario.getText();
       String contraseña = new String(txtPassword.getPassword());
       
       inicioSesion logeo = new inicioSesion();
       
       boolean acceso = logeo.consultaInicioSesion(usuario, contraseña);
       if(acceso){
           JOptionPane.showMessageDialog(this, "Bienvenido, " + usuario ,
                   "Sesión Exitosa", JOptionPane.INFORMATION_MESSAGE);
                   inicio Inicio_Ventana = new inicio();
                   Inicio_Ventana.setVisible(true);
        dispose();
       }else{
           JOptionPane.showMessageDialog(this, "Credenciales incorrectas",
                   "Advertencia", JOptionPane.NO_OPTION);
       }
    }//GEN-LAST:event_entrarMouseClicked
   
    
    //cuando el mouse entra al pane el color cambie 
    private void entrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseEntered
        // TODO add your handling code here:
        paneldentrar.setBackground(new Color (0, 59, 136, 255));
        entrar.setForeground(Color.white);
       
    }//GEN-LAST:event_entrarMouseEntered
 
    //cuando el mouse entra al pane el color cambie al original
    private void entrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseExited
        // TODO add your handling code here:
        paneldentrar.setBackground(new Color (0, 65, 86, 255));
        entrar.setForeground(Color.black);
    }//GEN-LAST:event_entrarMouseExited

    //para quitar el texto en el text area de usuarios
    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        // TODO add your handling code here:
        if(txtUsuario.getText().equals("Ingrese su usuario")){
                txtUsuario.setText("");
                txtUsuario.setForeground(Color.black);
        }
        if(String.valueOf(txtPassword.getPassword()).isEmpty() ){
                txtPassword.setText("********");
                txtPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        // TODO add your handling code here:+
        if(String.valueOf(txtPassword.getPassword()).equals("********")){
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
        }
       if(txtUsuario.getText().isEmpty()){
           txtUsuario.setText("Ingrese su usuario");
           txtUsuario.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtPasswordMousePressed

    private void txtXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtXMouseClicked

    private void txtXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseEntered
        // TODO add your handling code here:
        bt.setBackground(Color.red);
        txtX.setForeground(Color.white);
    }//GEN-LAST:event_txtXMouseEntered

    private void txtXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseExited
        // TODO add your handling code here:
        bt.setBackground(new Color(26,46,63));
        txtX.setForeground(Color.white);
    }//GEN-LAST:event_txtXMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen(), y =evt.getYOnScreen();
        this.setLocation( x- xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bt;
    private javax.swing.JLabel contrat;
    private javax.swing.JLabel entrar;
    private javax.swing.JPanel header;
    private javax.swing.JPanel paneldentrar;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel txtX;
    private javax.swing.JLabel usuart;
    // End of variables declaration//GEN-END:variables
}
