/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import clases.descuento;
import java.awt.Color;

/**
 *
 * @author FRANCIS
 */
public class Descuentos extends javax.swing.JFrame {

    /**
     * Creates new form Descuentos
     */
  
    int xMouse, yMouse;
    public Descuentos() {
        initComponents();
        cargarDescuentos();
    }

    private void cargarDescuentos(){
       txtDescuento1.setText(String.valueOf(descuento.getPrimerDescuento()));
       txtDescuento2.setText(String.valueOf(descuento.getSegundoDescuento()));
       txtDescuento3.setText(String.valueOf(descuento.getTercerDescuento()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescuento1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescuento2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescuento3 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        bt = new javax.swing.JPanel();
        txtX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("1 a 5 unidades");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, 30));

        txtDescuento1.setForeground(new java.awt.Color(153, 153, 153));
        txtDescuento1.setText("Descuento 1");
        txtDescuento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDescuento1MousePressed(evt);
            }
        });
        fondo.add(txtDescuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 180, -1));

        jLabel2.setText("6 a 10 unidades");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 30));

        txtDescuento2.setForeground(new java.awt.Color(153, 153, 153));
        txtDescuento2.setText("Descuento 2");
        txtDescuento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDescuento2MousePressed(evt);
            }
        });
        fondo.add(txtDescuento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, -1));

        jLabel3.setText("11 a 15 unidades");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 20));

        txtDescuento3.setForeground(new java.awt.Color(153, 153, 153));
        txtDescuento3.setText("Descuento 3");
        txtDescuento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDescuento3MousePressed(evt);
            }
        });
        fondo.add(txtDescuento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 180, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        fondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 80, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        bt.setBackground(new java.awt.Color(255, 255, 255));

        txtX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtX.setText("X");
        txtX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btLayout = new javax.swing.GroupLayout(bt);
        bt.setLayout(btLayout);
        btLayout.setHorizontalGroup(
            btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        btLayout.setVerticalGroup(
            btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(488, Short.MAX_VALUE)
                .addComponent(bt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtXMouseClicked

    private void txtXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseEntered
        // TODO add your handling code here:
        bt.setBackground(Color.red);
        txtX.setForeground(Color.white);
    }//GEN-LAST:event_txtXMouseEntered

    private void txtXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseExited
        // TODO add your handling code here:
        bt.setBackground(Color.white);
        txtX.setForeground(Color.black);
    }//GEN-LAST:event_txtXMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen(), y =evt.getYOnScreen();
        this.setLocation( x- xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void txtDescuento1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescuento1MousePressed
        // TODO add your handling code here:        
                if(txtDescuento1.getText().equals(String.valueOf(descuento.getPrimerDescuento()))){
                    txtDescuento1.setText("");
                    txtDescuento1.setForeground(Color.black);
                } 
                if(txtDescuento2.getText().isEmpty()){
                txtDescuento2.setText(String.valueOf(descuento.getSegundoDescuento()));
                txtDescuento2.setForeground(Color.gray);
       }
                if(txtDescuento3.getText().isEmpty()){
                txtDescuento3.setText(String.valueOf(descuento.getTercerDescuento()));
                txtDescuento3.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDescuento1MousePressed

    private void txtDescuento2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescuento2MousePressed
        // TODO add your handling code here:
                if(txtDescuento2.getText().equals(String.valueOf(descuento.getSegundoDescuento()))){  
                txtDescuento2.setText("");  
                txtDescuento2.setForeground(Color.black);
        }
                if(txtDescuento1.getText().isEmpty()){
                txtDescuento1.setText(String.valueOf(descuento.getPrimerDescuento()));
                txtDescuento1.setForeground(Color.gray);
       }
                if(txtDescuento3.getText().isEmpty()){
                txtDescuento3.setText(String.valueOf(descuento.getTercerDescuento()));
                txtDescuento3.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtDescuento2MousePressed

    private void txtDescuento3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescuento3MousePressed
        // TODO add your handling code here:
               if(txtDescuento3.getText().equals(String.valueOf(descuento.getTercerDescuento()))){
                txtDescuento3.setText("");  
                txtDescuento3.setForeground(Color.black);
        }
                if(txtDescuento2.getText().isEmpty()){
                txtDescuento2.setText(String.valueOf(descuento.getSegundoDescuento()));
                txtDescuento2.setForeground(Color.gray);
       }
                if(txtDescuento1.getText().isEmpty()){
                txtDescuento1.setText(String.valueOf(descuento.getPrimerDescuento()));
                txtDescuento1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDescuento3MousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Descuentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bt;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDescuento1;
    private javax.swing.JTextField txtDescuento2;
    private javax.swing.JTextField txtDescuento3;
    private javax.swing.JLabel txtX;
    // End of variables declaration//GEN-END:variables
}
